# Generated by Django 5.1.3 on 2024-11-15 17:20

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(blank=True, null=True, validators=[board.models.price_validator]),
        ),
    ]
