# Generated by Django 5.1.4 on 2024-12-09 18:04

import my_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sensitive_data', my_site.models.EncryptedField(unique=True)),
            ],
        ),
    ]
