# Generated by Django 5.1.4 on 2024-12-10 16:43

import my_site.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=my_site.models.PhoneNumberFieldUA(max_length=13, validators=[my_site.models.PhoneNumberFieldUA.validate_ua_number]),
        ),
    ]
