# Generated by Django 5.1.4 on 2024-12-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_alter_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile',
            new_name='user',
        ),
    ]
