"""empty message

Revision ID: 973694868914
Revises: 
Create Date: 2025-01-10 12:42:16.927158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973694868914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RENTED', 'MAINTENANCE', 'AVAILABLE', 'ON_HOLD', name='itemstatus'), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('price_per_day', sa.Float(), nullable=False),
    sa.Column('price_per_week', sa.Float(), nullable=False),
    sa.Column('price_per_month', sa.Float(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('user')
    # ### end Alembic commands ###
