"""sss

Revision ID: a0276947aca8
Revises: 407d35e790ca
Create Date: 2025-01-14 18:04:37.260009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0276947aca8'
down_revision = '407d35e790ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=250), nullable=True))
        batch_op.drop_column('name desription')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name desription', sa.VARCHAR(length=250), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
